import { Button } from "@/atoms/Button";
import { Chip } from "@/atoms/Chip";
import { Panel } from "@/atoms/Panel";
import { Text } from "@/atoms/Text";
import { estimateReadiness, getAgent } from "@/api/client";
import { EmptyState } from "@/molecules/EmptyState";
import { InsightList } from "@/molecules/InsightList";
import { KpiCard } from "@/molecules/KpiCard";
import { useAppState } from "@/state/AppState";
import styles from "./DashboardPage.module.scss";

const RING_CIRCUMFERENCE = 2 * Math.PI * 52;

export function DashboardPage() {
  const { report, setPage } = useAppState();
  const readiness = estimateReadiness(report);
  const gaps = getAgent(report, "SkillGapAgent")?.gaps || [];
  const match = getAgent(report, "JobMatchingAgent");
  const jobs = report?.matched_jobs || [];

  if (!report) {
    return (
      <EmptyState
        icon="◎"
        title="No readiness report yet"
        description="Upload a resume and run analysis to unlock your dashboard."
        actionLabel="Go to Upload"
        onAction={() => setPage("upload")}
      />
    );
  }

  const ringOffset = RING_CIRCUMFERENCE * (1 - readiness / 100);

  return (
    <div className={styles.stack}>
      <div className={styles.grid}>
        <Panel span={7} className={styles.hero}>
          <div className={styles.heroInner}>
            <div className={styles.ringWrap}>
              <svg viewBox="0 0 120 120" className={styles.ring}>
                <defs>
                  <linearGradient id="scoreGradient" x1="0%" y1="0%" x2="100%" y2="100%">
                    <stop offset="0%" stopColor="#1f7aef" />
                    <stop offset="55%" stopColor="#7c5cff" />
                    <stop offset="100%" stopColor="#12a39a" />
                  </linearGradient>
                </defs>
                <circle className={styles.ringTrack} cx="60" cy="60" r="52" />
                <circle
                  className={styles.ringFill}
                  cx="60"
                  cy="60"
                  r="52"
                  stroke="url(#scoreGradient)"
                  strokeDasharray={RING_CIRCUMFERENCE}
                  style={{ strokeDashoffset: ringOffset }}
                />
              </svg>
              <div className={styles.ringValue}>
                <strong>{readiness}</strong>
                <span>readiness</span>
              </div>
            </div>
            <div className={styles.heroCopy}>
              <span className={styles.kicker}>Career readiness</span>
              <h2>
                {report.target_role}{" "}
                <em>
                  {report.seniority_level || "Junior"} fit
                </em>
              </h2>
              <p className={styles.lead}>{match?.strengths?.[0] || "Match signal pending"}</p>
              <div className={styles.barTrack}>
                <div className={styles.barFill} style={{ width: `${readiness}%` }} />
              </div>
              <p className={styles.decisionNote}>
                {report.explainability?.decision_note || "Decision generated by the orchestrator."}
              </p>
            </div>
          </div>
        </Panel>

        <Panel span={5} delay={1}>
          <div className={styles.head}>
            <h2>Quick insights</h2>
            <Chip>{report.job_source || "curated"}</Chip>
          </div>
          <InsightList
            compact
            items={[
              `Top gap: ${gaps[0] || "None critical"}`,
              `Job source: ${report.job_source || "curated"}`,
              `Memory: ${report.explainability?.memory_note || "First analysis for this candidate"}`,
              `Report ID: ${report.report_id?.slice(0, 8) || "—"}`
            ]}
          />
          <div className={styles.actions}>
            <Button variant="secondary" onClick={() => setPage("gaps")}>
              Review Gaps
            </Button>
            <Button variant="primary" onClick={() => setPage("plan")}>
              Open Hiring Sprint
            </Button>
          </div>
        </Panel>
      </div>

      <div className={styles.kpiGrid}>
        <KpiCard
          label="Readiness Score"
          value={`${readiness}%`}
          hint={report.explainability?.decision_note?.slice(0, 80) || "From orchestrator"}
          tone="blue"
          icon="◎"
        />
        <KpiCard
          label="Detected Skills"
          value={String(report.profile.skills.length)}
          hint="Structured resume extraction"
          tone="teal"
          icon="⌘"
        />
        <KpiCard
          label="Priority Gaps"
          value={String(gaps.length)}
          hint="Highest impact missing skills"
          tone="amber"
          icon="▲"
        />
        <KpiCard
          label="Matched Jobs"
          value={String(jobs.length)}
          hint={`Source: ${report.job_source || "curated"}`}
          tone="rose"
          icon="◆"
        />
      </div>

      <div className={styles.grid}>
        <Panel span={12} delay={2}>
          <div className={styles.head}>
            <div>
              <span className={styles.kicker}>Job Matching Agent</span>
              <h2>Matched opportunities</h2>
            </div>
            <Chip>{report.job_source || "curated"}</Chip>
          </div>
          {jobs.length === 0 && <Text muted>No job matches returned for this run.</Text>}
          <div className={styles.jobList}>
            {jobs.slice(0, 6).map((job) => (
              <article className={styles.jobCard} key={job.id}>
                <div className={styles.jobHead}>
                  <h3>{job.label}</h3>
                  {typeof job.match_score === "number" && (
                    <span className={styles.matchBadge}>
                      {Math.round(job.match_score * 100)}%
                    </span>
                  )}
                </div>
                <Text muted tiny>
                  {job.company || "Company n/a"} · {job.source}
                </Text>
                <Text>{job.description_snippet || "No description snippet."}</Text>
                {job.required_skills?.length > 0 && (
                  <div className={styles.skillRow}>
                    {job.required_skills.slice(0, 6).map((skill) => (
                      <span className={styles.skillChip} key={skill}>
                        {skill}
                      </span>
                    ))}
                  </div>
                )}
                {job.url ? (
                  <a className={styles.jobLink} href={job.url} target="_blank" rel="noreferrer">
                    Open listing →
                  </a>
                ) : null}
              </article>
            ))}
          </div>
        </Panel>
      </div>
    </div>
  );
}
